### ISSUE TITLE
[Frontend] Phenotype redesign

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1058]
# Issue
This issue will resolve some tasks within:
- #960 

# Tasks
1. [x] Incorporate SCSS into CL
2. [x] Create components from current phenotype creation page
3. [x] Port phenotype page with new components
4. [x] Create draft designs:
    - [x] Panel to create rulesets
    - [x] Create rulesets through inputs e.g. search->ruleset, import->ruleset
5. [x] Finalise UI design
