### ISSUE TITLE
Dynamic templating, search, filters and more

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1076]
# Tasks
### SCSS implementation
- [x] Integrate SASS
- [x] Incorporate into new ```base_scss.html```
- [x] Create base components & layouts

### Component-based templating
- [x] Navigation and footer for ```base.html```
    - [ ] Update design's navigation bar to have multilevel dropdown support for admin-related component(s)
    - [ ] Finish footer implementation
- [x] Entity card renderer for search page
    - [x] Clinical entity card
    - [x] Generic entity card
- [x] Pagination renderer

### Statistics
- [x] Integrate statistics into each dynamic model's template
- [x] Implement method to track and update statistics through a job
- [x] Implement method to track and update statistics of metadata across all entities
    - [x] Metadata statistics relative to each model
    - [x] Global metadata statistics
- [ ] Discuss whether we want to implement simple analytics for entities while we're building from scratch?
    - e.g. hit count, export count, fork count?
    - Can be implemented into `GenericEntity` model using signals and receivers

### Filters
- [x] Create frontend components for filters
- [ ] Implement backend for filters
- [ ] Dynamic filter renderer for search page
- [ ] Frontend service to interface with backend
    - [ ] Incorporate pagination controller

### Search
- [x] Create frontend components for search results e.g. cards
- [ ] Implement backend for search
- [ ] Implement dynamic templating

### Javascript-driven components and utilities
- [x] Navigation
- [x] Tagify
- [x] Stickytables
- [ ] Datepicker
- [ ] Datatables
- [ ] Dropdowns that aren't driven by CSS

### Breadcrumbs
- [x] Port breadcrumbs.py for 'automated' breadcrumb generation
- [ ] Modify Breadcrumbs so that the resolvers function with CL's method of creating URLs / etymology of urls
- [ ] Test across older pages

### Clinical phenotype creation and update via web interface
- [x] Create design for clinical phenotype creation
- [ ] Implement backend for create and update methods
- [ ] Implement frontend controller
