### ISSUE TITLE
[Grouped Tasks] Entity/Concepts/Data integrity

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1105]
# Pull requests
- #1111 
- #1125

# Tasks
### Design
1. [x] Search icon interactivity on search page
2. [x] Small design fixes
3. [x] Improve create cards

### Entity Class changes
1. [x] Improve admin form to excl. user fields - should have been auto added
2. [x] Add user and time related metadata for admin use

### Create renderer
1. [x] Bug → Group select on organisation field doesn't allow deselect of group
2. [x] Add PhenoflowID to clinical creation

### Search / Filter renderer
1. [x] Render templates contextually i.e. by given entity class
2. [x] Improve logic for deriving related entities
3. [x] If no stats found for computed fields, ignore and generate sourced references instead

### Access & Permissions
1. [x] Change perms back to `None`, `View`, `Edit`
2. [x] Create Mixin or Decorator for RO access
3. [x] Add decorator to create/update/publish pages

### Backend
1. [x] URL transfer for MC
2. [x] Add param to stop attribute getter during concept serialisation
3. [x] Correct the status codes being used for invalid requests in `CreateEntityView` methods
4. [x] Allow modifier for source getter
5. [x] Improve template version handling
6. [x] Alter Concept review method
    - Review code is now separated from published code → ¿do we need to change code duplication checker?

### Data integrity
1. [x] New migratory method for phenotypes results in error to rest of code - discussed with @elmessary, will examine why occurs & implement fix 
    - Done but issues surrounding Django-Simple-History & PSQL's AutoField as discussed in #1091
2. [x] Fix issues relating to DSH for migration
