### ISSUE TITLE
[Post-redesign] User Account Management

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1108]
# Issue
As previously discussed, we are in need of finalising our implementation of UAM. Before finalising design of user pages, found in #1106, we should reconsider this issue to avoid repetition of work if we are required to move to another UAM implementation.

Previous issue can be found here:
- #782 

# Considerations
1. Authentication methods e.g. password-based auth, SSO etc
2. User flow, e.g. registration, and changes to current methods of restoring account
3. User profile integration, which links to @ieuans implementation of the _My Collection_ page
4. Organisation & Memberships, which links to previous work within the private repo [here](https://github.com/JackScanlon/CLDevSuite/tree/master/app/apps/organisation)
    - Currently rely on Django's Group system which has several significant limitations for what we're attempting to use it for
5. Changes to permission methods
    - Links to the (4), where we rely on the Group permission method, rather than individual and/or personalisable permission methods

# Tasks
1. [x] Tasks related to #782
2. [ ] Discuss requirements and possible solutions
3. [ ] Implement prior to #1106

**Comment by JackScanlon** [comment]
Superseded by new HDRN requirements
