### ISSUE TITLE
Styleguide for new design components

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1116]
# Issue
Relates to SCSS components after redesign

# Tasks
- [ ] Ensure all components meet same standard of flexibility
- [ ] Create styleguide for each type of component
- [ ] Examples for each component
