### ISSUE TITLE
Update URL patterns

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1123]
# Issue
Our models are now dynamic and their names and prefixes meet the pattern of `\w+`, e.g. `PH1`, `WS1`. 

We need to update all related URLs to meet this pattern, instead of relying on a token like `?P<pk>PH\w+` since it will not always be the case that the prefix is `PH`

# Tasks
- [ ] Update all patterns to match `\w+` e.g. `details/(?P<entity_id>\w+)/`
- [ ] Modify any code that expects tokens to match specific entity prefixes within the view resolvers
- [ ] Test all modified URL patterns
