### ISSUE TITLE
Hold and display a user version in addition to our internal version IDs

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1133]
Create a new field for version
New phenotpypes will default to 1 and increment
existing phenotypes default to current latest version and then increment

**Comment by JackScanlon** [comment]
# Tasks
1. Modify historic models to have a user-facing `version_id`
    - [ ] Modify the historic models
    - [ ] Create new save manager to increment the `version_id` for each individual instance
    - [ ] Update all existing methods to use the new `version_id`
    - [ ] Update all frontend / backend code to use the new `version_id`

**Comment by JackScanlon** [comment]
Marking as stale
