### ISSUE TITLE
Modify create interface

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1172]
# Issue
Grouped issue relating to design & behaviour of create/update interface

# Tasks
- [x] Create/Update methods are blocked in RO access
- [x] Hide the cards in RO access
- [x] Improve selector for components
- [x] Improve accessibility for tab traversal
- [x] Add button for queries
- [x] Block request until promise resolves
