### ISSUE TITLE
Update home page designs

### ISSUE THREAD

**Issue by ieuans** [SwanseaUniversityMedical/concept-library#1175]
### Update
Artur is going to update HDRUK brand, so task should be amended to create all home page designs other than HDRUK

### Task

1. [x] Finalise home page designs with wider group, see below
2. [x] Update home page designs (all brands) to use SCSS, most components should already exist in the components/ folder but may require new components incl. use new navigation and footer components so all pages are consistent & use brand map in _brands.scss
3. [x] Search bar on homepage should redirect to the single search page

### To discuss
- HDRUK remains the same? See [here](https://www.figma.com/file/7Hct08x5DxbxC4HMB2LM7T/Phenotype-Library?type=design&node-id=329-1364)
- SAIL & Base concept library mimics HDRUK page but uses different assets for the search bar? 
- Does ADP require an updated page?
- HDRUK stats updated in task #1236
