### ISSUE TITLE
Changes to Phenotype Builder

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1200]
# Issue

Feedback has been received for the Phenotype Builder and Concept Creator - requires some changes to the interface, the creation flow and has highlighted some issues with our data.

Also contains fixes for bugs that were found within my testing for other dev's codebase(s) - the team should review the changes I've made to their code

# Tasks
## Frontend bugs
- [x] `<aside/>` navigation children partially occludes creation wizard - no visual impact, but does result in strange input behaviour when highlighting text.
  - [x] Modify size constraints of `<aside/>`
  - [x] Test to ensure no overflow across devices
- [x] The legacy URL resolvers for prev. models & their associated views have been removed, but the links are still present in `base.html`; need to remove these and move to new resolvers
- [x] Date validation issue(s) within datepicker & daterange components

## Data changes & issues
- [x] Template specific filter queries for brands or other complex filters
  - [x] `DataTypeFilters` class within _'filter_utils.py'_ that can handle dynamically generated parameters and to return a valid query that can be executed via ORM
  - [x] Update methods to use the RequestContext to derive sourced values by templates/metadata if required by its filters
  - [x] Assoc. validation methods
- [x] Add 'Neither' option to the sex field within the clinical template
- [x] Add 'Other' option to the phenotype type field
- [x] DataSource duplicated rows - resulted from historic use of scrapers to generate data
  - [x] Examine the data to det. instances of duplication
  - [x] Create _'data_utils.py'_ and create generalised method of analysing models for duplicate rows for future usage
  - [x] Discussed with team r.e. sync & dupl. rows

## Backend changes
- [x] Reset `publish_status` post-update
- [x] Test validation methods to account for new UI requirements e.g. text input for dates
- [x] Add brand relation when creating / updating an object
  - [x] Migration for brands from Collection → Brand
  - [x] Create permission methods for brands & update existing brand-related logic
  - [x] Test & validate

## Frontend changes
- [x] _'Create an Entity'_ UI / UX
  - [x] Replace every instance of _'entity'_ with _'phenotype'_ prior to demo
  - [x] Modify _entitySelection.js_ renderer such that:
    - [x] Remove SPA-like selection interface
    - [x] Each `EntityClass` is given a subheading and a scrollable container containing each of its child `Template` instances
- [x] _'Clinical Coded Phenotype'_ UI / UX
  - [x] Sex field changes
    - [x] Use checkboxes instead of radiobutton for the 'Sex' field - need new renderer
    - [x] Make context aware component to allow selection of both 'Male' and 'Female' to create 'Male/Female' internally, but emulate radiobutton behaviour when 'Neither' is selected
    - [x] Ensure field type is extensible and reusable - probably has to be integrated into template
    - [x] Create new client-sided validator
  - [x] Date range picker field
    - [x] Change client-side validation method to work with strings instead of date objects
    - [x] Remove the datepicker component and use an inputbox instead per Slack feedback
    - [x] Assoc. frontend components
- [x] _'Concept'_ UI / UX
  - [x] Changes to components
    - [x] Update the UI to use _'Rule'_ instead of _'Ruleset'_
    - [x] Increment the _'New Concept'_ and _'New Rule'_ components so that they are rendered with names that follow the pattern of `'New Rule %d' % n + 1`
    - [x] Modify the colours & icons in the column fields that describe code inclusion for rulesets per the feedback
  - [x] QoL changes
    - [x] Sort coding system alphabetically
    - [x] Sort rendered dropdowns alphabetically
  - [x] Impl. method to differentiate between owned/unowned Concepts
    - [x] Pass ownership to template via utility methods
    - [x] Disallow changes if unowned
  - [x] Ability to edit search terms
    - [x] Impl. diff method for change in search terms
    - [x] Reimpl. aggregation, codelist and source methods
    - [x] Client-sided validation methods need to be changed
    - [x] Test new methods
