### ISSUE TITLE
Ensure each brand has a default collection that is auto allocated when user creating new phenotype

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1204]
# Tasks
> [!] Note: Would also probably be a good time to split up Tags and Collections
- [x] Discuss requirements of Brand, and the distinction between Collections (i..e `Tag`) and Brands
- [x] Allocate the Brand to the entity instance rather than allocating a Collection
  - [x] Can also be derived from Collections
- [x] Modify migration script to perform this task during Pheno->GenericEntity transfer & split up the Tag/Collection fields
- [x] Update permission methods
