### ISSUE TITLE
Tags & Collections

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1223]
# Issue
The `Tag` model defines both `Tags` and `Collections`, and are allocated to either group through an enumerator. As these are two distinct types of data, we should be using two separate models.

# Complexities
- The `Tag` object holds both _Tags_ and _Collections_ which results in inefficiencies during queries
- Transforming the data via endpoints results in inefficiencies as a result of either joining or splitting up the data to manipulate it
- Using the same model restricts the data it can hold, as well as its functionality, which will make it difficult to support user-generated tags/collections in future iterations of CL

# Tasks
- [ ] Split up `Tag` and `Collection` instances
- [ ] Modify utility methods, templates, and other methods to account for this change
- [ ] Migrate the DB

**Comment by Hannah-Davies** [comment]
closing as no longer required following new phenotype template design
