### ISSUE TITLE
Fix issues after changes made to accessible entities

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1226]
# Issue
The changes made by commit #1606556 causes issues with search and API views

# Tasks
- [x] Changes did not account for the requirement that results to be distinct
- [x] `publish_status` OR `world_access` - setting a published phenotype to `world_access=WORLD_ACCESS.NONE` shouldn't work
- [x] Add brand logic to `get_accessible_entities` method
- [x] Test
