### ISSUE TITLE
Change in requirements to Templates

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1250]
# Tasks / Changes

- [x] Add _'Name & Author'_ section to all templates
- [x] Combine sections of ./create and ./detail
- [x] `template_details` field is used to derive the `name` and `description` of the Template model
- [x] Add card & version within `template_details`
- [x] Clean all metadata-related fields from the template
- [x] Don't allow Template control over ordering/rendering of permission-related data
- [x] Test changes across `phenotype`, `working_set`, and `structured_data_algorithm`
