### ISSUE TITLE
Phenotype Builder bugs & changes

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1254]
# Issues
### Validation & Activity
- @elmessary noticed that:
  - The mandatory property is ignored for `valid_event_date_range`
  - That I had accidentally set `event_date_range`'s `active` property to `false`
- Upon further testing, it was revealed that this was also ignored for the `phenoflowid` field due to how the value was being parsed, e.g. if the value was `null` it would throw an exception when parsing since it would result in a `NaN` value

### Rendering
- `null` values for `inputbox` fields would render as `None`

# Tasks
### Bug fixes
- [x] Fix client side validation within entityCreator.js
- [x] Fix server side validation for null, non-mandatory fields
- [x] Fix to rendering of values if `null`

### Changes
- [x] Added a prompt to inform user they should save their progress on child components before attempting to submit the form
- [x] Methods to determine interaction state of components
- [x] Better retrieval of field data
