### ISSUE TITLE
Statistics changes

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1274]
# Issue
- Stats no longer functional after changes to template
- Collection of stats can be simplified now that `publish_status` has been implemented

# Tasks
- [x] Fix stats after changes to template
- [x] Improve performance of stats
- [x] Caching of templates and sourced data within stats
