### ISSUE TITLE
Session cleanup

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1303]
# Issue
Current sessions exceeds ~100mb because they haven't been purged - see Django reference [here](https://docs.djangoproject.com/en/4.2/topics/http/sessions/#clearing-the-session-store)

# Tasks
- [x] Flush the session via `logout()` method on session expiry
  - [x] Add settings to control `IDLE` and `SESSION` expiry times
- [x] Django management command to flush expired sessions
- [x] Cronjob to purge expired sessions on a weekly basis
