### ISSUE TITLE
Changes to base scss

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1306]
# Issue
Scaling issue for monitors on `.main-header` and `.main-content`

# Tasks
- [x] Apply changes to all pages once design merges have been completed#
- [x] Test changes across pages to ensure style is valid
- [x] Move page styles into pages, move components into components
- [x] Add missing docs
