### ISSUE TITLE
Compression, Cache busting & Static serving

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1326]
# Issue
- We need to handle cache invalidation for locally stored copies of static files
- We need to compress our styles & frontend code, incl. transpiling ES6→ES5 for portability & compression (via `esbuild` and `django-compressor`)
- We need to enable GZip compression - better SEO (see this [reference](https://help.siteimprove.com/support/solutions/articles/80000448464-why-is-gzip-compression-being-flagged-as-an-seo-issue-)) & performance

# Discussion
WhiteNoise can be removed as a dependency from this PR since we're using Apache to serve static files, it serves as a demonstration for local testing before moving to prod.

We'll be using [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/4.2/ref/contrib/staticfiles/#manifeststaticfilesstorage) to hash and invalidate files.

# Tasks
### Demo
- [x] Set up `esbuild` with `django-compressor`
- [x] Set up storage
- [x] Set up compression
- [x] Fix static file errors from legacy code base
- [x] Append to prod deployment workflow
- [x] Set up demo for static serving
- [x] HTML compression
- [x] Reformat `settings.py`

### Once agreed
- [x] Confirm prod deployment workflow
- [x] Ensure Apache is set up for GZip compression
- [x] Employ GZip middleware - put HTML compressor before GZip

# Related tasks
Partially relates to:
- #1095
