### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1384]
# Issue
Unused imports, and possibly unused required packages, contributing to bloat

# Tasks
- [x] Remove unused imports
- [x] Removed unused packages

# Auxiliary tasks
- [x] Replace `distutils` method calls - no longer supported in Py 3.10+
- [x] Rewrite imports
