### ISSUE TITLE
Todo before production

### ISSUE THREAD

**Issue by ieuans** [SwanseaUniversityMedical/concept-library#1394]
# Todo

#### Documentation
- [x] [Ieuan & Jack] Finalise new README, see: [#concept-library-channel](https://hiru.slack.com) or [README.md](https://github.com/SwanseaUniversityMedical/concept-library/blob/JS/cleanup-workspace/README.md)

#### Before merging
- [x] [Jack] Make backup branches of master, HDRUK and DTFM before merging, see:
  - https://github.com/SwanseaUniversityMedical/concept-library/tree/Legacy-Master
  - https://github.com/SwanseaUniversityMedical/concept-library/tree/Legacy-Development
  - https://github.com/SwanseaUniversityMedical/concept-library/tree/Legacy-HDR-UK

#### Database issues
- [x] [Muhammad] Resolve EMIS migration

#### Data quality
- [x] [Jack] Generate new column with longest description for reference data, see: commit https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/0c5884f5ee41d3d59fed74a5ff9e69f3c4946588
  - Set up gin indexing for new columns

#### Cleaning the project
- [x] [Jack] Clean up legacy code, see: PR #1386  
- [x] [Jack] Impl. dockerfile & release changes for CI / CD, see: https://github.com/SwanseaUniversityMedical/concept-library/pull/1401/commits/d16963893187ed969de8c3b77432901f31a5c90c
- [x] [Jack] Solve conflicts for rebase, see: #1400 and #1401
  - Note: Should merge 1401 into 1400 before merge, see reference issues

#### Testing Containers
- [x] [Jack] Test deploy using new script
  - [x] [Jack] Script issue, see: commit https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/025de0f9c4877ab76e7d0a8fef2efaaf1a999b26
  - [x] [Jack] Fix foreign key constraint issue after truncation due to stale data, see: commit https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/be104d93ab87d1f0a4eb3d3645fdac2084dec24d

#### Refactoring Python Concept Library Client
- [x] [Ieuan] Update the `pyconceptclient`, see: https://github.com/SwanseaUniversityMedical/pyconceptlibraryclient/commit/2cd5cdf7911ed49274227d897be98fce339e678f
  - [x] Add in missing functionality
  - [x] Fix issues
  - [x] Refactor code
  - [x] Finish documentation

#### Documentation
- [x] [Ieuan] Add pyconceptclient URL to API page
- [x] [Ieuan] Write README's for R and Python API client packages
- [x] [Ieuan] Update R man/, see: https://github.com/SwanseaUniversityMedical/ConceptLibraryClient/commit/5a7fad89689f9b64f06cb7e51d3c3be5150b9510
- [x] [Ieuan] Update GitHub wiki
  - [x] Write new Wiki
  - [x] Upload to Github [**_once merged_**]

#### Testing
- [x] [Ieuan] Test both packages on current version of API
  - [x] [Ieuan] Resolve issues found with R package, and update documentation, see: https://github.com/SwanseaUniversityMedical/ConceptLibraryClient/commit/d741af861727585c33bdf18b9cb781154f8c7ad4

#### Emailing
- [x] [Artur] Emailing results of a review
- [x] [Ieuan] Test emailing system

#### Development
- [x] [Jack] Add Mailhog to test container to avoid any further email issues, see commit: https://github.com/SwanseaUniversityMedical/concept-library/commit/b06ebcc317595e211c05ddd05a9cf2b218fbc16d and https://github.com/SwanseaUniversityMedical/concept-library/commit/4bf8dd9b145695fb5201f568f12ca0a89177ef62

#### Navigation bar
- [x] [Artur] Resolve resizing issues with dropdowns (mobile)
- [x] [Artur] Highlighting issue for about pages in navigation bar, see: https://github.com/SwanseaUniversityMedical/concept-library/pull/1389

#### Detail page
- [x] [Muhammad] Hide fields or show `no data` when null in metadata? See: PH392, valid_event_date_range
- [x] [Ieuan] Import/Export on detail page to reflect the ConceptLibraryClient and pyconceptclient package, see: https://github.com/SwanseaUniversityMedical/concept-library/commit/4b1766be01bd9b1345b2af3cc776b5b5925c376b
- [x] [Ieuan] Lowercase `s` in `search > [phenotype_name]` breadcrumb, see: https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/4b1766be01bd9b1345b2af3cc776b5b5925c376b
- [x] [Jack] Concept isn't shown as `Legacy Version` in detail page for out of date Concepts, see commit: https://github.com/SwanseaUniversityMedical/concept-library/pull/1401/commits/9185ea0ec70471fb360f3287943092cff318255c
- [x] [Jack] Removed jQuery code being used and replaced it with ES6, see: commit https://github.com/SwanseaUniversityMedical/concept-library/commit/3a93628ed83f9339fcd975dfc53fad8815bd28ba

#### Homepage
- [x] [Dan] Copywriting for homepage, see: [Google Sheets document](https://docs.google.com/spreadsheets/d/1ar9L4HPEty5D5rfbg66mnmyqqCo6CkfbNyUsDBqCkYA/edit#gid=0)
  - [x] [Dan] Copywriting for Phenotypes, Codelists, Data Sources, Clinical Codelists and Clinical Terminologies
  - [x] [Dan] Copywriting for ‘What do we do?’ section
- [x] [Jack] Update homepage once with copywriting once complete, see: https://github.com/SwanseaUniversityMedical/concept-library/commit/93ac0e35075c2e4480af30f233c268601ee118ec

#### Archive
- [x] [Jack] Archive & Restore Phenotypes, see: https://github.com/SwanseaUniversityMedical/concept-library/commit/059a2435e1e19cc843e764a0d66a5e3d59739abf and https://github.com/SwanseaUniversityMedical/concept-library/commit/1edeb9bf12402ccc959ee936357f8c72524de37f

#### Search
- [x] [Jack] Search resource failure, see: #1404 

#### Concept linkage issues
> ***[!] Note:** See: https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/d15c86ff59624cee9bbc7a7f80f3727d24895394 && https://github.com/SwanseaUniversityMedical/concept-library/pull/1400/commits/1e732af30c40a781ec5e3ac2379797d4f4a3cfba*  
- [x] [Jack] Create pgsql script to determine unlinked Concepts and produce a report, see [#concept-library-development](https://hiru.slack.com) channel
- [x] [Jack] Implement method to migrate all Concepts to a pseudo-Phenotype
- [x] [Jack] Redirect all Concept URLs to Phenotype URLs

#### Documentation
- [x] [Dan] Review documentation
- [x] [Jack] Add Documentation viewer inside Clinical Code List editor, see: commit https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/c506ef1a51152a5d0f1605967e4748df8b3120cb

#### Small enhancements
- [x] [Jack] Impl. the small changes post-feedback, see: commit https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/c506ef1a51152a5d0f1605967e4748df8b3120cb and https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/9045f5a069582daee618e7e9d90fed5ca8d2f4c4
- [x] [Jack] Ability to remove and restore phenotypes, see: https://github.com/SwanseaUniversityMedical/concept-library/issues/1396
- [x] [Jack] Some enhancements, see: commit https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/3a93628ed83f9339fcd975dfc53fad8815bd28ba
  - Improve chips
  - Add filter to code list size on import
  - Add coding system term to import
  - Add 'Migrate to Latest version' for imported Concepts in the Create page

## Permissions
> ***[!] Note:** [Jack] I noticed an issue with some of the permission methods that were being used in other PRs and decided to fix them before prod. See commit for changes: https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/dadd414a50d9648e2e69934fd6113b1fe4a1a7fe and https://github.com/SwanseaUniversityMedical/concept-library/commit/80e7cc58d2242f27c2f3ac6e8f5e5369ed965fa5*  

- [x] [Jack] Remove and fix legacy permission methods that relied upon `Published` models
- [x] [Jack] Add methods to check Concept `publication_status` using the new `phenotype_owner` and its parent Phenotype's `publish_status` fields

#### Pre-production discussions
- [x] [Dan] Discuss how should we handle Concept links going forward? → Decided we'll migrate all Concepts to Phenotypes

#### Misc. development tasks
>***[!] Note:** [Jack] These tasks relate to misc. issues I found when testing the app locally*  

- [x] [Jack] The HDRUK stats in `stat_utils.py` can break if a template, such as WorkingSets or Structured Data Algorithms, doesn't include the fields it expects - looks like a lot of this came from the legacy site hence its lack of stability. In the meantime, I have created a temporary fix, but in reality, this needs to be fixed by the tasks described in #1276. 
  - For now though, see: commit https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/1b6259ea50cb26de888f83695dfdf5e6c1d32198
- [x] [Jack] Set up `urls.py` for production use, and prepend read-only conditionals to template URLs, see: commit https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/b22b16446d8bf377496885912cfde07ad607cc26
- [x] [Jack] Fix read-only URLs, see: commit https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/e1f85f63b9befcfc506bd7a236a6157aec08b0c8
