### ISSUE TITLE
Changes to collections & archivable phenotypes

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1396]
# Issue
Several helpdesk tickets and other feedback requesting ability to archive phenotypes

# Tasks
- [x] Ability to archive phenotypes
- [x] Ability to edit phenotypes from within `My Collection` page
- [x] Ability to restore phenotypes
- [x] Other small enhancements & fixes

# Pull Requests
See:
- Removal: https://github.com/SwanseaUniversityMedical/concept-library/pull/1386/commits/059a2435e1e19cc843e764a0d66a5e3d59739abf
- Restoration: https://github.com/SwanseaUniversityMedical/concept-library/pull/1401/commits/1edeb9bf12402ccc959ee936357f8c72524de37f
