### ISSUE TITLE
Search resource failure

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1404]
# Issue
Resource error when attempting to search on feature domain

# Tasks
- [x] Bug causing search failure
- [x] Improve safety of query parameters
- [x] Improve performance of search
