### ISSUE TITLE
Atlas Phenotypes

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1408]
# Specification
1. Store the definitions currently used for the prognostic Atlas in the Library as simple Phenotypes

# Status
Mostly blocked until data is available and #1409 is completed:

- [x] Contact repository owner to get access to data 

# Notes
Some differences between a _'Clinical Coded Phenotype'_ and an _'Atlas Phenotype'_:
- The former is composed of one or more code lists, each of their own coding system, containing one or more codes
- The latter is composed of a single _'Phecode'_ - defined as _'Phecodes are manually curated groups of International Classification of Diseases (ICD) codes intended to capture clinically meaningful concepts for research.'_

To support Atlas Phenotypes, we will likely need a custom component on the create page to allow individuals to select a Coding System and an associated Phecode - in contrast to a Clinical Coded Phenotype, which allows the creation of Concepts.

# Tasks

### Atlas Phenotype uploading
1. [x] Get access to the repository
2. [x] Plan out new `Template` model for these entities

### Required actions

> ***Note:** Discuss with wider HDRUK group before continuing*  

Need to:
1. Parse & upload the available data as individual phenotypes
