### ISSUE TITLE
Pharmacological Phenotypes - BHF

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1430]
# Goal

The goal would be to support Phenotypes that could contain data relating to pharmacology and pharmaceutics to aid in the research undertaken during clinical trials & drug development.

# Tasks
> ***[!] Note:** Still TBD, but the following items were discussed in the previous meeting*  
- [x] Plan and undertake scoping with collaborators
- [x] Plan trial and update existing template (dont think we need to create a new `Template`) to support this, incl. scoping new features that may be required to support these Phenotypes - production demo site
- [x] Testing functionality of versioning templates to ensure working

BHF will upload phenotypes themselves
