### ISSUE TITLE
Template descendant search changes & improvements

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1535]
# Issue

### Summary
- Descendant search showed poor performance with some of the more complex queries taking in excess of a ~300 - 500ms - note that this _excludes page loading_ time
    - This is due to the complexity of the `Concept` model and its related models, _e.g._ `Component` → `CodeList` → `Code` and their historical counterparts
    - Requires non-naive method of computing descendants that can be applied to dynamic models, as is the case with the `Phenotype` model and its associated `Template` model
- Other issues included:
    - Not filtering the current `Phenotype` from the returned results
    - Issues surrounding pagination as a result of the aforementioned model complexity

### Tasks
- [x] Rewrite `get_template_entities` logic to improve behaviour and computation time
- [x] Determine & implement optimal method of querying across all of the associated models dynamically
    - [x] Assess and improve accuracy of results
    - [x] Better validation of descendant field(s)
- [x] Implement better method of pagination
