### ISSUE TITLE
Disease / Specialty Classification Hierarchy - API Backend and Utilities

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1570]
# Issue

## Summary

Changes required to current API to support ontology tags, and new API endpoint needed to support ontologies.

## Tasks
- [x] Template-related methods to derive readable ontology data
- [x] Ontology endpoints
  - [x] All ontology types
  - [x] Per ontology type
  - [x] Per ontology instance
