### ISSUE TITLE
Disease / Specialty Classification Hierarchy - Front End Design incl. Reference & Detail Page Changes

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1571]
# 1. Issue

### 1.1. Summary

Continuation of previous Disease / Specialty Classification task sets. This task relates to the requirements & implementation of front-end components related to cards, the reference & detail page.

### 1.2. Related tasks
- #1462 

# 2. Tasks

### 2.1. Design

- [x] Discuss design requirements
- [x] Prepare design & user story examples

### 2.2. Implementation

- [x] ~~Implement card design~~ - ***Note:** no longer required*
- [x] Implement detail page design
- [x] Implement reference data page
