### ISSUE TITLE
HDRN: Design Custom Template

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1732]
# 1. Summary

> [!IMPORTANT]  
> The `Size` of this task may be incorrectly allocated to `Small`; if the fields require custom component(s) then this issue's `Size` should be updated to relfect that

## 1.1. Overview

Design and implement a template to support HDRN requirements

## 1.2. Preparation

> [!NOTE]  
> Please see up-to-date documents in the `#concept-library-dev` channel, _e.g._ ... 
> - `Concept Template Edit.docx`;
> - `algorithm_export.xlsx`;
> - ... _etc_

Assess template requirements described by the following documents:

- `CIPHER Phenotype Collection Form Review.docx`
- `ICES Concept Dictionary - template OCT.docx`
- `MCHP Concept Development Template.pdf`

# 2. Tasks

- [ ] Create HDRN Template with required fields
- [ ] Implement any new components required to support templates
- [ ] Test template functionality

**Comment by roshantoby** [comment]
[Concept Template Edits.docx](https://github.com/user-attachments/files/19226308/Concept.Template.Edits.docx)
