### ISSUE TITLE
HDRN: Design & Apply Branding

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1733]
# 1. Summary

## 1.1. Overview

Design and apply branding of the National Concept Dictionary in support of HDRN deployment.

## 1.2. Preparation

Assess supporting documents that describe the brand requirements before developing a design that satisfies these requirements:
- Consider the communication style requirements defined within `Communication Style Guide.pdf`
- Consider HDRN's [website](https://www.hdrn.ca/en/)

# 2. Tasks

- [x] Implement changes to HDRN-related brand and its stylesheet
    - [x] Apply brand colours
    - [x] Apply font requirements
- [x] Logo branding
    - [x] Source & apply HDRN's logo
    - [x] Source & apply the branded favicon
    - [x] Source & apply the branded `apple-touch-icon`
- [x] Component changes
    - [x] Update header content → update '_About_' content
    - [x] Update footer content → update footer branding, _incl._ icons

**Comment by roshantoby** [comment]
[Communications Style Guide.docx.pdf](https://github.com/user-attachments/files/19163762/Communications.Style.Guide.docx.pdf)
