### ISSUE TITLE
HDRN: Supporting References & Labels

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1736]
# 1. Summary

## 1.1. Overview

Source and manage references required to support HDRN deployment.

## 1.2. Preparation

Assess required assets:
- See HDRN discussion(s) concerning assets of `province`, `data asset` _etc_
- Assess feasibility of MeSH labeling alongside SNOMED

# 2. Tasks

- [ ] References
    - [ ] Source & upload assets
    - [ ] Implement any changes required to support these items
- [ ] Labeling
    - [ ] Source MeSH terminology
    - [ ] Consider implementing MeSH map
