### ISSUE TITLE
HDRN: Coding Systems Requirements

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1737]
# 1. Summary

> [!IMPORTANT]  
> The `Size` of this task may have been incorrectly allocated to `Small` depending on the complexity of how the Coding System assets have been provisioned; if parsing the resources are more complex than expected then this issue's `Size` should be updated to reflect that

## 1.1. Overview

Source and manage Coding Systems required by HDRN.

## 1.2. Preparation

Assess assets:
- [x] ICD-10-CA
- [x] ICD-9-CM
- [x] ATC/DDD
- [x] MeSH (ontology) 

# 2. Tasks

- [x] Create models to support each of the Coding Systems
- [x] Source Coding System resources
- [x] Parse resources and coerce into required structure
- [x] Upload coding system assets
