### ISSUE TITLE
HDRN: Administration

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1738]
# 1. Summary

## 1.1. Overview

Implement administration management for brand associated content.

## 1.2. Preparation

Assess requirements:
- See HDRN discussion(s) related to administration

# 2. Tasks

## 2.1. Task Allocation

Agreed assignment of tasks are as follows:
- Backend → @roshantoby 
- Frontend → @JackScanlon 

## 2.2. Backend Tasks

- [ ] User role model:
    - [ ] Create new user role to support brand administration
    - [ ] Implement permission logic to support management access and privileges
- [ ] Implement View/Controller to support branded administration rendering with methods to support:
    - [ ] Ability to override administration of groups & content
    - [ ] Ability to create user accounts
    - [ ] Ability to manage user privileges

## 2.3. Frontend Tasks

- [ ] Interface to support branded administration of users & groups:
    - [ ] Component(s) to create user accounts & to manage user privileges
    - [ ] Component to override administration of groups
- [ ] Interface to support branded administration of content:
    - [ ] Component to assess moderation queue ± update publication status
    - [ ] Component to control & archive content
