### ISSUE TITLE
HDRUK: Graph demo

### ISSUE THREAD

**Issue by ieuans** [SwanseaUniversityMedical/concept-library#1747]
# 1. Overview
Investigate graph frameworks for Atlas researcher -> development pipeline & integration with CL

Future implications on:
- Data syncing of labels/categories, e.g. medical specialities
- Graph display within Atlas & CL (large datasets)

# 2. Tasks
- [x] Plotly impl.
    - [x] SVG
    - [x] WebGL
- [x] Apache ECharts
- [x] D3js impl.
    - [x] Investigate render frameworks
    - [x] PIXI impl.
- [x] Data handling
   - [x] Investigate frameworks
   - [x] Apache arrow impl.
- [x] Temp. host demo for the meeting
- [x] R->Web pipeline

**Comment by JackScanlon** [comment]
Marking as complete
