### ISSUE TITLE
Look at best way to update owner of concept / phenotype to enable publishing

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#772]
# Issue

1. Currently only the owner can publish a concept / phenotype and only the owner can change the owner.  it is not realistic for owners of concepts / phenotypes to change the owner to someone else if they leave an organisation etc.  Therefore need to look at the best way to enable members of a group to publish if not owner or to be able to update the owner to publish

2. Do we need to put a specific user as the owner for loaded Phenotypes, right now it is Ieuan? per #410 

# Tasks
1. [x] Create new Permission model that each content-based model and its historical model references
    - [x] Permission model
    - [x] Migrate current data to use new model
    - [x] Create new permission methods and decorators
2. [x] During migration, update owners of the phenotype to their respective group instead of `Ieuan`
