### ISSUE TITLE
investigate DOI tool to import publication data/model design

### ISSUE THREAD

**Issue by elmessary** [SwanseaUniversityMedical/concept-library#981]

**Comment by JackScanlon** [comment]
# Related
Accessory issue located at:
- #1032 → closed in favour of #981

# Tasks
- [x] Investigate methods to incorporate and publish phenotypes with DOI
- [x] Present findings to group
- [ ] Awaiting meeting to finalise details and progress further

**Comment by JackScanlon** [comment]
Marking as stale
